# Generated by Django 4.2.8 on 2023-12-06 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientForSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpellIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Witch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('coven', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witch', to='witchesapi.avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WitchIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('healing_property', models.CharField(max_length=200)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witchIngredient', to='witchesapi.ingredienttype')),
                ('witch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witchIngredient', to='witchesapi.witch')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('intention', models.CharField(max_length=200)),
                ('chant', models.CharField(max_length=500)),
                ('when_most_powerful', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('other_instructions', models.CharField(max_length=500)),
                ('favorite', models.BooleanField(default=False)),
                ('ingredients', models.ManyToManyField(related_name='spells', through='witchesapi.IngredientForSpell', to='witchesapi.spellingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientforspell',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientForSpell', to='witchesapi.spell'),
        ),
        migrations.AddField(
            model_name='ingredientforspell',
            name='spellIngredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientForSpell', to='witchesapi.spellingredient'),
        ),
    ]
