# Generated by Django 4.2.8 on 2023-12-15 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('healing_property', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('intention', models.CharField(max_length=200)),
                ('chant', models.CharField(blank=True, max_length=500)),
                ('repeat_chant', models.IntegerField(blank=True, default=0, null=True)),
                ('when_most_powerful', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('instructions', models.CharField(max_length=500)),
                ('additional_info', models.CharField(blank=True, max_length=400)),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Witch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('coven', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witch', to='witchesapi.avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WitchInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witch_inventory', to='witchesapi.witch')),
            ],
        ),
        migrations.CreateModel(
            name='WitchInventoryIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=200)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witches_inventory_ingredients', to='witchesapi.ingredient')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_ingredients', to='witchesapi.witchinventory')),
            ],
        ),
        migrations.CreateModel(
            name='SpellIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(blank=True, max_length=300)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells_ingredients', to='witchesapi.ingredient')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells_ingredients', to='witchesapi.spell')),
            ],
        ),
        migrations.CreateModel(
            name='SpellEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells_equipment', to='witchesapi.equipment')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells_equipment', to='witchesapi.spell')),
            ],
        ),
        migrations.AddField(
            model_name='spell',
            name='equipment',
            field=models.ManyToManyField(related_name='spells', through='witchesapi.SpellEquipment', to='witchesapi.equipment'),
        ),
        migrations.AddField(
            model_name='spell',
            name='ingredients',
            field=models.ManyToManyField(related_name='spells', through='witchesapi.SpellIngredient', to='witchesapi.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='witchesapi.ingredienttype'),
        ),
    ]
