# Generated by Django 4.2.8 on 2023-12-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witchesapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='repeat_chant',
            field=models.IntegerField(default=0),
        ),
    ]
